from solutions import day11_1, day11_2


def test_part1():
    input_str = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#....."""
    assert day11_1.solve(input_str) == 374


def test_part2():
    input_str = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#....."""
    assert day11_2.solve(input_str, 9) == 1030
    assert day11_2.solve(input_str, 99) == 8410
